# Données historiques extraites du PDF "Projets Maintenance - Commande Pièces.pdf".
# Cette liste alimente uniquement la table commandes lors de la migration V6.

COMMANDES_HISTORIQUES = [{'date': '2026-07-27',
  'piece': 'Raccord 1/2 mal vers clips tuyau blanc dia 12',
  'quantite': '2',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': "Prévoir également pour l'ERS"},
 {'date': '2026-07-27',
  'piece': 'Raccord en T Prevost pour tube dia 20 PPS1',
  'quantite': '2',
  'reference': 'PPS1 TT2012',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': 'Allimentation de la machine en air comprimée'},
 {'date': '2026-05-20',
  'piece': 'PE Prises pupitre V3',
  'quantite': '3',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2026-05-20',
  'piece': 'Sacoche Console Siemens',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2026-02-12',
  'piece': 'Clips pour fermer les capots de chemin de câbles',
  'quantite': '100',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2026-01-27',
  'piece': 'Disjoncteur 3P courbe C 40A Schneider',
  'quantite': '1',
  'reference': 'A9F77340',
  'etat': 'Refusé',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'PG Armoire Pompes'},
 {'date': '2026-01-19',
  'piece': 'Embase Coffret Femelle / Prise Mâle 4P+1T 2,5mm2 (Visser ou Enfichable) câble de dia 18mm',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2026-01-19',
  'piece': 'Disjoncteur 2P C10A',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': 'Protection fontaine'},
 {'date': '2026-01-19',
  'piece': 'Disjoncteur Legrand 2P 3A',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': 'Protection secondaire transfo'},
 {'date': '2026-01-19',
  'piece': 'Disjoncteur Legrand 2P 2A',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': 'Protection primaire transfo'},
 {'date': '2026-01-19',
  'piece': 'Boutons poussoir Noir',
  'quantite': '10',
  'reference': 'XB4BA25',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2026-01-19',
  'piece': 'Goulottes 25X60',
  'quantite': '2m',
  'reference': '43260961 (WL)',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2026-01-19',
  'piece': 'Poignée sectionnement interrupteur sectionneur 3P 12A Schneider',
  'quantite': '1',
  'reference': 'VCF02',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-12-15',
  'piece': 'GREEN FLASH TXPLUS-2',
  'quantite': '5L',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-12-09',
  'piece': 'Dérouleur eau pour v6',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-12-09',
  'piece': 'Vanne PVC pour tube 40mm et tête de chat',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': '18 ou 20G1mm^2',
  'quantite': '5m',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': 'Prise raccordement bi-manuelle 18 ou 20 pin prise câble mâle et fiche coffret femelle',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'BP Orange avec LED 48V',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'BP AU Rouge',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-10-28',
  'piece': 'Disjoncteur tri 16A 30mA et 15k pouvoir de coupure (prise chauffage réfectoire et vestiaire)',
  'quantite': '2',
  'reference': '',
  'etat': 'Commandé',
  'delai': '2025-12-04',
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-10-27',
  'piece': 'Prise pour capteurs blocage broyeur',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'ACTI9 IC60H 1P-N 4A C DIS JONCTEUR MINIAT (Pompe à fioul)',
  'quantite': '1',
  'reference': 'A9F84604',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': 'Délai indiqué dans le PDF : ?'},
 {'date': '2025-05-14',
  'piece': 'Porte étiquettes rond pour BP (Imprimante)',
  'quantite': '?',
  'reference': 'https://products.cembre.com/fr/france/family/1270',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Porte étiquettes repérage fil avec étiquettes à glisser taille 1mm² - 1,5mm² - 2,5mm² - 4mm² - 6mm² '
           '(Imprimante)',
  'quantite': '?',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Etiquettes repérage S7-1500 (Imprimante)',
  'quantite': '?',
  'reference': '',
  'etat': 'Demandé',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-11-27',
  'piece': 'WAGO double et triple',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': 'Coffret 600X600X300',
  'quantite': '1',
  'reference': 'NSYS3D6630P',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': 'Pattes de fixation coffret',
  'quantite': '1',
  'reference': 'NSYAEFPFSC',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': 'Plaque de fond coffret pré-percée',
  'quantite': '1',
  'reference': 'NSYTSAKFL',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-25',
  'piece': 'Coffret prises maintenance 400X400X200',
  'quantite': '1',
  'reference': 'NSYS3D4420P',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Thermique Moteur 2,2A',
  'quantite': '2',
  'reference': 'GV2ME07',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Contacteur 3P 48V',
  'quantite': '2',
  'reference': 'LC1D12E7',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Relais de bi-manuelle 48V',
  'quantite': '1',
  'reference': 'XPSUS32AP',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': "Relais d'arrêt d'urgence 48V",
  'quantite': '1',
  'reference': 'XPSUAK32AP',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Poignée de sectionnement coffret',
  'quantite': '1',
  'reference': 'VCF02',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Commutateur 2 Positions Accrochage',
  'quantite': '2',
  'reference': 'XB4BD33',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Protection général coffret 3P 6A',
  'quantite': '1',
  'reference': 'A9F77306',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Vanne et filtre pneumatique cadenassable',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Protection primaire transfo 2P 1A',
  'quantite': '1',
  'reference': 'A9F74201',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-11-24',
  'piece': 'Protection secondaire transfo 2P 6A',
  'quantite': '1',
  'reference': 'A9F75206',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Perceuse Double',
  'commentaire': ''},
 {'date': '2025-10-30',
  'piece': 'Capteur datalogic tauring',
  'quantite': '1',
  'reference': 'S5-5-C35-32',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': 'Câble commandé 04/12'},
 {'date': '2025-10-28',
  'piece': 'Prises pour coffret établi Fernand',
  'quantite': '6',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-12-04',
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-10-27',
  'piece': 'Disjoncteur tri 16A 30mA ( alimentation perceuse )',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-12-04',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-10-27',
  'piece': 'Disjoncteur 20A PHASE NEUTRE, 30mA (alimentation prises dérouleur)',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-12-04',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-10-16',
  'piece': 'Commutateur 3 position avec retour au centre',
  'quantite': '2',
  'reference': 'XB5AD53',
  'etat': 'Livré',
  'delai': '2025-12-04',
  'chantier': 'Refendeuse',
  'commentaire': ''},
 {'date': '2025-10-16',
  'piece': 'Interrupteur éclairage extension bâtiment stockage',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-10-16',
  'piece': 'Prise et câble poste à souder bleu',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-10-16',
  'piece': 'Tête caoutchouc vérins poussoirs Robot',
  'quantite': '50',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': '',
  'commentaire': ''},
 {'date': '2025-09-25',
  'piece': 'Bloc prise simple avec clapet étanche',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-09-25',
  'piece': 'Bloc prise simple sans clapet étanche',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-09-25',
  'piece': 'Bloc prises double avec support mural et clapet étanche',
  'quantite': '2',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-09-23',
  'piece': 'Écrou PG13,5 PE Plastique Skintop',
  'quantite': '50',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-09-10',
  'piece': 'Projecteurs LED "sans lumandare"',
  'quantite': '2',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Montage Galets',
  'commentaire': ''},
 {'date': '2025-09-08',
  'piece': 'Câble terre 1,5mm2',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-09-08',
  'piece': 'Câble 2,5mm2 Noir',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Gaine thermo',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'ComPacT NSX - Cache-borne court - 4P - pour NSX100-250',
  'quantite': '1',
  'reference': 'LV429518',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Peignes Bornes Entrelec 2.5',
  'quantite': '50 / 10',
  'reference': '1SNK905310R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Peignes Bornes Entrelec 4',
  'quantite': '50 / 10',
  'reference': '1SNK906310R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Peignes Bornes Entrelec 6',
  'quantite': '50 / 10',
  'reference': '1SNK908310R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Bornes Entrelec ZK6-PE',
  'quantite': '20',
  'reference': '1SNK708150R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Bornes Entrelec ZK6',
  'quantite': '50',
  'reference': '1SNK708010R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Bornes Entrelec ZK2.5',
  'quantite': '200',
  'reference': '1SNK705010R0000',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-08-26',
  'piece': 'Carte Automate Logo DM824R',
  'quantite': '1',
  'reference': '6ED1055-1HB00-0BA2',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Convoyeurs Broyeurs V2 V3',
  'commentaire': '3'},
 {'date': '2025-08-26',
  'piece': 'Obturateur trou BP Schneider',
  'quantite': '100',
  'reference': 'ZB5SZ3',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-08-20',
  'piece': 'Multiprise pour PC Mag Auto',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-08-20',
  'piece': 'Resi9 - disjoncteur différentiel - 1P+N - 16A - 30mA - courbe C - type Fsi',
  'quantite': '1',
  'reference': 'A9DK1616',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': 'Délai indiqué dans le PDF : ?'},
 {'date': '2025-08-20',
  'piece': 'Prise de courant modulaire 16A 2P+T standard français 250V',
  'quantite': '2',
  'reference': 'A9A15306',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': 'Prise Consôle Armoire Mag Auto | Délai indiqué dans le PDF : ?'},
 {'date': '2025-08-20',
  'piece': 'Acti9 iC60N - Disjoncteur - 1P+N - 1A - Courbe C - 230Vca - 6000A/50kA',
  'quantite': '1',
  'reference': 'A9F74601',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': 'Départ EV Air comprimé | Délai indiqué dans le PDF : ?'},
 {'date': '2025-08-20',
  'piece': 'Relais Finder 24VDC',
  'quantite': '10',
  'reference': 'FIN465290240040 FIN9702SPA',
  'etat': 'Livré',
  'delai': '2025-09-05',
  'chantier': 'Mag Auto',
  'commentaire': 'EV Air comprimé'},
 {'date': '2025-08-05',
  'piece': 'Acti9 iC60N - Disjoncteur - 3P - 10A - Courbe C - 400Vca - 6000A/10kA',
  'quantite': '4',
  'reference': 'A9F77310',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': 'Réf différente : A9P24310'},
 {'date': '2025-08-05',
  'piece': 'Acti9 iC60N - Disjoncteur - 1P+N - 20A - Courbe C - 230Vca - 6000A/10kA',
  'quantite': '1',
  'reference': 'A9F77620',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Rail DIN',
  'quantite': '10m ?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'ComPacT NSX100F - disjoncteur - TM-D 50A - 4P4D - 36kA - montage fixe',
  'quantite': '1',
  'reference': 'C10F4TM050',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'ComPacT NSX - Commande rotative prolongée standard - poignée noire pour NSX250',
  'quantite': '1',
  'reference': 'LV429338T',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'ComPacT NSX - Cache-borne court - 4P - pour NSX100-250',
  'quantite': '1',
  'reference': 'LV429518',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Linergy DS - Répartiteur étagé tétrapolaire - 160A - 4x12 trous',
  'quantite': '1',
  'reference': 'LGY416048',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9, iID interrupteur différentiel 4P 40A 30mA type AC',
  'quantite': '1',
  'reference': 'A9R11440',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Linergy DS - Répartiteur étagé tétrapolaire - 125A - 4x15 trous',
  'quantite': '1',
  'reference': 'LGY412560',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9 iC60N - Disjoncteur - 1P+N - 10A - Courbe C - 230Vca - 6000A/10kA',
  'quantite': '4',
  'reference': 'A9F77610',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9 iC60N - Disjoncteur - 1P+N - 16A - Courbe C - 230Vca - 6000A/10kA',
  'quantite': '3',
  'reference': 'A9F77616',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9 iC60N - Disjoncteur - 1P+N - 32A - Courbe C - 230Vca - 6000A/10kA',
  'quantite': '2',
  'reference': 'A9F77632',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9 iDT40N - Disjoncteur modulaire - 3P+N - 20A - Courbe C - 6000A/10kA',
  'quantite': '1',
  'reference': 'A9P24720',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'TeSys LC1D - contacteur - 4P - AC-1 440V - 40A - bobine 24Vcc',
  'quantite': '1',
  'reference': 'LC1DT40BD',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Linergy DS - Répartiteur étagé tétrapolaire - 100A - 4x7 trous',
  'quantite': '1',
  'reference': 'LGY410028',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Acti9 C60H-DC - Disjoncteur modulaire - 2P - 5A - Courbe C',
  'quantite': '1',
  'reference': 'A9N61525',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Linergy DS - Répartiteur étagé tétrapolaire - 125A - 4x15 trous',
  'quantite': '1',
  'reference': 'LGY412560',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Cosses à oeillets 6x8-6',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Cosses à oeillets 10x8-6',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Cosses à oeillets 35x8-6',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Cosses à oeillets 50x8-6',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Goulotte 60LX60H avec couvercle',
  'quantite': '10m ?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Goulotte 40LX60H avec couvercle',
  'quantite': '10m ?',
  'reference': '',
  'etat': 'Livré',
  'delai': '2025-08-14',
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-07-10',
  'piece': 'Pince à sertir (cosses)',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-06-24',
  'piece': 'Connecteurs RJ45 Siemens',
  'quantite': '6',
  'reference': '6GK19011BB102AA0',
  'etat': 'Livré',
  'delai': '2025-07-03',
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-06-24',
  'piece': 'IHM Siemens KTP700 Basic',
  'quantite': '1',
  'reference': '6AV2123-2GB03-0AX0',
  'etat': 'Livré',
  'delai': '2025-07-03',
  'chantier': 'Tour Aéro',
  'commentaire': 'Produit sur RS'},
 {'date': '2025-06-24',
  'piece': 'Commutateur 3 positions a accrochage 28mm',
  'quantite': '1',
  'reference': '9001KS43FB et 9001KA1 ?',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Parachèvement V2',
  'commentaire': ''},
 {'date': '2025-06-17',
  'piece': 'Couronne fils 1mm2 rouge',
  'quantite': '100m',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-06-17',
  'piece': 'Couronne fils 1mm2 bleu',
  'quantite': '100m',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-27',
  'piece': 'TeSys GV - contact auxiliaire - 1O+1F',
  'quantite': '3',
  'reference': 'GVAN11',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'Pompes 3-8-7'},
 {'date': '2025-05-27',
  'piece': 'TeSys GV2ME - disj. moteur - 9..14A - 3P 3d - déclencheur magnéto-thermique',
  'quantite': '3',
  'reference': 'GV2ME16',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'Pompes 3-8-7'},
 {'date': '2025-05-27',
  'piece': 'TeSys LC1D - contacteur - 3P - AC-3 440V - 12A - bobine 24Vcc',
  'quantite': '4',
  'reference': 'LC1D12BD',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'Pompes 3-8-7 et chauffage'},
 {'date': '2025-05-27',
  'piece': 'Harmony XB4 - tête bouton arrêt urgence - Ø40 - pousser tourn - rouge',
  'quantite': '2',
  'reference': 'ZB4BS844',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'Intérieur et extérieur'},
 {'date': '2025-05-27',
  'piece': 'TeSys D - bloc contacts auxiliaires frontaux - 4F+0O - bornes vis-étriers',
  'quantite': '2',
  'reference': 'LADN40',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'KAU 1 et 2'},
 {'date': '2025-05-27',
  'piece': 'Carte 16DI/16D0 S7-1200 24VDC 16DI/16D0',
  'quantite': '1',
  'reference': '6ES7223-1BL32-0XB0',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-19',
  'piece': 'PT100 Extérieure',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-19',
  'piece': 'Cable PT100',
  'quantite': '100m ?',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-19',
  'piece': 'Carte Analogique S7-1200 X8 AI',
  'quantite': '1',
  'reference': '6ES7231-4HF32-0XB0',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': 'Ou 2*4'},
 {'date': '2025-05-16',
  'piece': 'Projecteurs LED "sans lumandare"',
  'quantite': '5',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Connecteurs RJ45 Siemens',
  'quantite': '2',
  'reference': '6GK19011BB102AA0',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Relais Finder 24VDC',
  'quantite': '10',
  'reference': 'FIN465290240040 FIN9702SPA',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Borne Terre Entrelec 2,5mm²',
  'quantite': '50',
  'reference': '1SNK705150R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Borne Terre Entrelec 4mm²',
  'quantite': '25',
  'reference': '1SNK706150R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Borne simple Entrelec 2,5mm²',
  'quantite': '100',
  'reference': '1SNK705010R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Fin de borne Entrelec 2,5mm² Simple',
  'quantite': '50',
  'reference': '1SNK705910R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Fin de borne Entrelec 2,5mm² Double',
  'quantite': '50',
  'reference': '1SNK705911R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Stop borne Entrelec',
  'quantite': '50',
  'reference': '1SNK900002R0000',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Câble 12G1mm²',
  'quantite': '100m',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Fil 1mm² Noir',
  'quantite': '1 bobine',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Bouchon Opturateur (Trous BP)',
  'quantite': '50',
  'reference': 'ZB5SZ3',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Fil 1,5mm² Rouge',
  'quantite': '1 bobine',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Cosses fil 1mm²',
  'quantite': '1000',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Cosses fil 1,5mm²',
  'quantite': '1000',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Cosses fil 4mm²',
  'quantite': '500',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': 'Cosses fil 6mm²',
  'quantite': '500',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-14',
  'piece': "Grille d'armoire 700x1400mm",
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Mag Auto',
  'commentaire': 'Fabrication maison ?'},
 {'date': '2025-05-14',
  'piece': 'Clips + Vis de fixation pour composants sur grille',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Maintenance',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'TeSys LC1D - contacteur - 3P - AC-3 440V - 25A - bobine 24Vcc',
  'quantite': '1',
  'reference': 'LC1D25BD',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'TeSys GV2ME - disj. moteur - 20..25A - 3P 3d - déclencheur magnéto-thermique',
  'quantite': '1',
  'reference': 'GV2ME22',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'TeSys LC1D - contacteur - 3P - AC-3 440V - 12A - bobine 24Vcc',
  'quantite': '4',
  'reference': 'LC1D12BD',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'TeSys GV - contact auxiliaire - 1O+1F',
  'quantite': '4',
  'reference': 'GVAN11',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Acti9 iC60N - Disjoncteur - 3P - 10A - Courbe C - 400Vca - 6000A/10kA',
  'quantite': '1',
  'reference': 'A9F77310',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Acti9 Contact Auxiliaire Bas niveau 1 OF - Courant 2mA à 100mA ca/dc',
  'quantite': '1',
  'reference': 'A9A26914',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'TeSys GV2ME - disj. moteur - 9..14A - 3P 3d - déclencheur magnéto-thermique',
  'quantite': '3',
  'reference': 'GV2ME16',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Prise de courant 230V étanche',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Intérrupteur double avec boitier',
  'quantite': '1',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Chemin de câble 75X51X0,75',
  'quantite': '?',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''},
 {'date': '2025-05-13',
  'piece': 'Vis pour éclisses M6X12mm (boulon TRCC tête ronde bombée à collet carré)',
  'quantite': '1 boite',
  'reference': '',
  'etat': 'Livré',
  'delai': None,
  'chantier': 'Tour Aéro',
  'commentaire': ''}]
